# Generated by Django 4.2.2 on 2025-04-21 05:45

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        VectorExtension(),
    ]