# Generated by Django 4.2.2 on 2025-06-02 07:16

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vectorstore', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Institution')),
                ('personid', models.CharField(max_length=200, unique=True, verbose_name='User name')),
                ('embedvec', pgvector.django.vector.VectorField(dimensions=512, help_text='Vector embeddings(Facenet512)', verbose_name='Embedding Vector of User')),
                ('imgfilename', models.CharField(max_length=200, unique=True, verbose_name='User image file')),
                ('modelid', models.CharField(max_length=30, verbose_name='AI model')),
                ('sim_imgfile1', models.CharField(max_length=200, null=True, verbose_name='Name of Top 1 similar image')),
                ('sim_imgfile2', models.CharField(max_length=200, null=True, verbose_name='Name of Top 2 similar image')),
                ('sim_image1', models.ImageField(null=True, upload_to='', verbose_name='Top 1 similar image')),
                ('sim_image2', models.ImageField(null=True, upload_to='', verbose_name='Top 2 similar image')),
                ('identify', models.BooleanField(default=False, verbose_name='Result Positive')),
                ('distance1', models.FloatField(null=True, verbose_name='Top 1 distance')),
                ('distance2', models.FloatField(null=True, verbose_name='Top 2 distance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Vecmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('personid', models.CharField(max_length=200, unique=True)),
                ('vectorid', models.IntegerField(blank=True, null=True, unique=True)),
                ('embedvec', pgvector.django.vector.VectorField(dimensions=512, help_text='Vector embeddings(Facenet512)')),
                ('imgfilename', models.CharField(max_length=200, unique=True)),
                ('modelid', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VecImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vecmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vectorstore.vecmanager')),
            ],
        ),
        migrations.CreateModel(
            name='SearchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('searchmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vectorstore.searchmanager')),
            ],
        ),
    ]
